version: "3.8"
services:

    web:
        image: nginx:latest
        container_name: nginx-container
        ports:
        - "8080:80"
        volumes:
        - ./:/var/www/firstweb
        - ./default.conf:/etc/nginx/conf.d/default.conf
volumes:
    db-data: ~
